language: cpp

install:
  - sudo apt-get install lcov
  - gem install lcoveralls

script:
  - cd mechanism/test
  - cmake .
  - make
  - ctest -V
  - cd -
  - cd platform/test/cmake_StdCppOSWrapperTest
  - cmake .
  - make
  - ctest -V
  - cd -
  - cd platform/test/cmake_PosixOSWrapperTest
  - cmake .
  - make
  - ctest -V
  - cd -

after_success:
  - sh tool/coverage.sh .
  - lcoveralls -r .
