version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: >-
    msbuild -p:PlatformToolset=v141 tool\CppUTest\CppUTest.vcxproj

    msbuild -p:PlatformToolset=v141 platform\test\PlatformOSWrapperTest\StdCppOSWrapperTest.vcxproj

    msbuild -p:PlatformToolset=v141 platform\test\PlatformOSWrapperTest\WindowsOSWrapperTest.vcxproj