version: 1.0.{build}
image:
- Visual Studio 2019
- Visual Studio 2022

configuration:
- Release
- Debug

environment:
  matrix:
  - ARCH: x86_64
  - ARCH: x86

matrix:
  fast_finish: true

install:
- python.exe -m pip install --upgrade pip
- python.exe -m pip install "conan>=2"
- cmd: conan profile detect

build_script:
- cmd: >-
    conan build mechanism/test --build=missing -s arch=%ARCH% -s build_type=%CONFIGURATION%

    conan build platform/test --build=missing -s arch=%ARCH% -s build_type=%CONFIGURATION% -o platform_os=STDCPP

    conan build platform/test --build=missing -s arch=%ARCH% -s build_type=%CONFIGURATION% -o platform_os=WINDOWS

    conan build mechanism --build=missing -s arch=%ARCH% -s build_type=%CONFIGURATION%

    conan create mechanism --build=missing -s arch=%ARCH% -s build_type=%CONFIGURATION%

    conan build platform --build=missing -s arch=%ARCH% -s build_type=%CONFIGURATION%

    conan create platform --build=missing -s arch=%ARCH% -s build_type=%CONFIGURATION%

