version: 1.0.{build}
image: Visual Studio 2019
install:
- cmd: git submodule update --init --recursive
build_script:
- cmd: >-
    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x86 tool\CppUTest\CppUTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x86 mechanism\test\AssertionTest\AssertionTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x86 mechanism\test\ContainerTest\ContainerTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x86 mechanism\test\OSWrapperTest\OSWrapperTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x86 platform\test\PlatformOSWrapperTest\StdCppOSWrapperTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x86 platform\test\PlatformOSWrapperTest\WindowsOSWrapperTest.vcxproj


    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x64 tool\CppUTest\CppUTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x64 mechanism\test\AssertionTest\AssertionTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x64 mechanism\test\ContainerTest\ContainerTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x64 mechanism\test\OSWrapperTest\OSWrapperTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x64 platform\test\PlatformOSWrapperTest\StdCppOSWrapperTest.vcxproj

    msbuild -p:PlatformToolset=v142;Configuration=Release;Platform=x64 platform\test\PlatformOSWrapperTest\WindowsOSWrapperTest.vcxproj