name: Coverage

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        pip install "conan>=2"
    - name: Create a default conan profile
      run: conan profile detect
    - name: Install lcov
      run: sudo apt install lcov

    - name: Coverage
      run: sh ${{github.workspace}}/tool/coverage.sh ${{github.workspace}}

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        path-to-lcov: ${{github.workspace}}/coverage_build/coverage.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
