name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        pip install "conan>=2"
    - name: Create a default conan profile
      run: conan profile detect
    - name: Install cppcheck
      run: sudo apt install cppcheck

    - name: Run static analysis
      run: sh ${{github.workspace}}/tool/cppcheck.sh ${{github.workspace}}

    - name: Run test
      run: sh ${{github.workspace}}/tool/run_test.sh ${{github.workspace}}

    - name: Build package
      run: sh ${{github.workspace}}/tool/build_package.sh ${{github.workspace}}
