name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install conan
      run: |
        python -m pip install --upgrade pip
        pip install "conan>=2"
    - name: Create a default conan profile
      run: conan profile detect

    - name: Run test
      run: sh ${{github.workspace}}/tool/run_test.sh ${{github.workspace}}
